theme = "mine"

[editor]
auto-pairs = false
bufferline = "always"
auto-format = true
insert-final-newline = true
trim-final-newlines = true
trim-trailing-whitespace = true
end-of-line-diagnostics = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
# ["diagnostics", "selections", "register", "position", "file-encoding"]
right = ["workspace-diagnostics", "separator", "selections", "separator", "register", "separator", "position", "separator", "file-encoding"]
# workspace-diagnostics = ["error"]
mode.normal = "normal"
mode.select = "select"
mode.insert = "insert"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.whitespace.render]
# space = "all"

[editor.soft-wrap]
enable = true
wrap-indicator = " â†ª  "

[keys.normal]
C-s = ":w"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"del" = "delete_selection"
# p = "paste_clipboard_after"
# P = "paste_clipboard_before"
# y = "yank_to_clipboard"
L = "expand_selection"
A = "shrink_selection"
I = "select_prev_sibling"
E = "select_next_sibling"
O = "insert_at_line_end"

[keys.normal.h]
h = "goto_next_diag"
k = "toggle_comments"
e = ":format"
w = ":buffer-close"
c = "goto_next_buffer"
l = "goto_previous_buffer"
o = "file_picker"
i = "collapse_selection"
a = ":wa"
s = "split_selection_on_newline"
p = "command_palette"

[keys.select]
C-s = ":w"

[keys.insert]
C-s = ":w"

[keys.select.h]
"," = "remove_primary_selection"

[keys.normal.m]
f = "flip_selections"

[keys.select.m]
f = "flip_selections"
