[user]
name = "SÃ¶nke Hahn"
email = "soenkehahn@gmail.com"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

[ui]
default-command = "diff"

[templates]
git_push_bookmark = '"soenkehahn/" ++ change_id.short()'
draft_commit_description = '''
concat(
  description,
  "\n",
  "JJ: This commit contains the following changes:\n",
  indent("JJ:    ", diff.stat(72)),
  "JJ: ignore-rest\n",
  diff.git(),
)
'''

[remotes.origin]
auto-track-bookmarks = "glob:*"
